### ISSUE TITLE
data

### ISSUE THREAD

**Issue by iceb8** [ChiefGokhlayeh/pluto-sdr-pr#120]
hi, this looks an interesting project. Could you please share / upload the data folder to be able to run the notebooks? Thanks

**Comment by ChiefGokhlayeh** [comment]
Unfortunately, I am unable to publicly disclose the recordings for this project, as it would be a conflict of interest with my current employer. 

Even with access to the data, this project is incomplete and didn't produce any bistatic plots. 
Note, this project was conducted during my undergrad studies by two students with lacking signal processing knowledge and basically zero guidance.
